export const luxembourgCommunes = [
  "Luxembourg-Ville",
  "Belair",
  "Limpertsberg",
  "Merl",
  "Cessange",
  "Kirchberg",
  "Bonnevoie",
  "Hollerich",
  "Gasperich",
  "Strassen",
  "Bertrange",
  "Mamer",
  "Mersch",
  "Junglinster",
  "Niederanven",
  "Sandweiler",
  "Walferdange",
  "Steinsel",
  "Hesperange",
  "Schuttrange",
  "Contern",
  "Roeser",
  "Frisange",
  "Mondorf-les-Bains",
] as const;

export const internationalRegions = [
  {
    region: "France",
    cities: ["Paris", "Cannes", "Nice", "Saint-Tropez"],
  },
  { region: "Monaco", cities: ["Monaco"] },
  { region: "Belgique", cities: ["Bruxelles"] },
  { region: "Suisse", cities: ["Genève", "Zurich"] },
  { region: "Allemagne", cities: ["Berlin", "Munich"] },
  { region: "Italie", cities: ["Milan", "Rome"] },
  {
    region: "Espagne",
    cities: ["Madrid", "Barcelone", "Marbella", "Ibiza", "Majorque"],
  },
  { region: "Portugal", cities: ["Lisbonne", "Porto", "Algarve"] },
  { region: "Émirats", cities: ["Dubaï", "Abu Dhabi"] },
  { region: "Amériques", cities: ["New York", "Miami", "Cancún", "Tulum"] },
  { region: "Océan Indien", cities: ["Île Maurice"] },
] as const;
