// Couverture Luxembourg : quartiers premium de la capitale + toutes
// les grandes communes du pays (Sud/Minette, ceinture Ouest, Moselle,
// Centre, Nord) — pas seulement la capitale. Étendu à la demande de
// Julien (Steinfort, Mamer, Capellen, Kehlen, Koerich, Hobscheid,
// Käerjeng, Dippach, etc.).
export const luxembourgCommunes = [
  // Luxembourg-Ville & quartiers premium
  "Luxembourg-Ville",
  "Belair",
  "Limpertsberg",
  "Merl",
  "Cessange",
  "Kirchberg",
  "Bonnevoie",
  "Hollerich",
  "Gasperich",
  "Gare",
  "Cents",
  "Clausen",
  "Weimerskirch",
  "Rollingergrund",
  "Beggen",
  "Dommeldange",
  "Neudorf",
  "Hamm",
  // Ceinture Ouest / Capellen
  "Strassen",
  "Bertrange",
  "Mamer",
  "Capellen",
  "Steinfort",
  "Kehlen",
  "Koerich",
  "Hobscheid",
  "Septfontaines",
  "Garnich",
  "Dippach",
  "Kopstal",
  "Leudelange",
  "Reckange-sur-Mess",
  // Sud / Minette
  "Esch-sur-Alzette",
  "Differdange",
  "Dudelange",
  "Pétange",
  "Sanem",
  "Belvaux",
  "Käerjeng",
  "Bascharage",
  "Bettembourg",
  "Schifflange",
  "Kayl",
  "Tétange",
  "Mondercange",
  "Rumelange",
  // Centre / Nord-Centre
  "Mersch",
  "Lintgen",
  "Lorentzweiler",
  "Walferdange",
  "Steinsel",
  "Bissen",
  "Colmar-Berg",
  "Junglinster",
  "Betzdorf",
  "Ettelbruck",
  "Diekirch",
  "Erpeldange-sur-Sûre",
  "Schieren",
  // Est / Moselle
  "Niederanven",
  "Schuttrange",
  "Contern",
  "Sandweiler",
  "Weiler-la-Tour",
  "Hesperange",
  "Roeser",
  "Frisange",
  "Dalheim",
  "Mondorf-les-Bains",
  "Remich",
  "Stadtbredimus",
  "Bous",
  "Wormeldange",
  "Grevenmacher",
  "Mertert",
  "Schengen",
  // Nord / Ardennes
  "Wiltz",
  "Clervaux",
  "Troisvierges",
  "Vianden",
  "Echternach",
  "Beaufort",
  "Larochette",
  "Redange",
  "Useldange",
  "Rambrouch",
] as const;

export const internationalRegions = [
  {
    region: "France",
    cities: ["Paris", "Cannes", "Nice", "Saint-Tropez"],
  },
  { region: "Monaco", cities: ["Monaco"] },
  { region: "Belgique", cities: ["Bruxelles"] },
  { region: "Suisse", cities: ["Genève", "Zurich"] },
  { region: "Allemagne", cities: ["Berlin", "Munich"] },
  { region: "Italie", cities: ["Milan", "Rome"] },
  {
    region: "Espagne",
    cities: ["Madrid", "Barcelone", "Marbella", "Ibiza", "Majorque"],
  },
  { region: "Portugal", cities: ["Lisbonne", "Porto", "Algarve"] },
  { region: "Émirats", cities: ["Dubaï", "Abu Dhabi"] },
  { region: "Amériques", cities: ["New York", "Miami", "Cancún", "Tulum"] },
  { region: "Océan Indien", cities: ["Île Maurice"] },
] as const;
